<h1><font color='blue'> 9E and 9F: Finding the Probability P(Y==1|X)</font></h1>

<h2><font color='Geen'> 9E: Implementing Decision Function of SVM RBF Kernel</font></h2>

<font face=' Comic Sans MS' size=3>After we train a kernel SVM model, we will be getting support vectors and their corresponsing coefficients $\alpha_{i}$

Check the documentation for better understanding of these attributes: 

https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
<img src='https://i.imgur.com/K11msU4.png' width=500>

As a part of this assignment you will be implementing the ```decision_function()``` of kernel SVM, here decision_function() means based on the value return by ```decision_function()``` model will classify the data point either as positive or negative

Ex 1: In logistic regression After traning the models with the optimal weights $w$ we get, we will find the value $\frac{1}{1+\exp(-(wx+b))}$, if this value comes out to be < 0.5 we will mark it as negative class, else its positive class

Ex 2: In Linear SVM After traning the models with the optimal weights $w$ we get, we will find the value of $sign(wx+b)$, if this value comes out to be -ve we will mark it as negative class, else its positive class.

Similarly in Kernel SVM After traning the models with the coefficients $\alpha_{i}$ we get, we will find the value of 
$sign(\sum_{i=1}^{n}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here $K(x_{i},x_{q})$ is the RBF kernel. If this value comes out to be -ve we will mark $x_{q}$ as negative class, else its positive class.

RBF kernel is defined as: $K(x_{i},x_{q})$ = $exp(-\gamma ||x_{i} - x_{q}||^2)$

For better understanding check this link: https://scikit-learn.org/stable/modules/svm.html#svm-mathematical-formulation
</font>

## Task E

> 1. Split the data into $X_{train}$(60), $X_{cv}$(20), $X_{test}$(20)

> 2. Train $SVC(gamma=0.001, C=100.)$ on the ($X_{train}$, $y_{train}$)

> 3. Get the decision boundry values $f_{cv}$ on the $X_{cv}$ data  i.e. ` `$f_{cv}$ ```= decision_function(```$X_{cv}$```)```  <font color='red'>you need to implement this decision_function()</font>

In [76]:
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification
import numpy as np
from sklearn.svm import SVC

In [77]:
X, y = make_classification(n_samples=5000, n_features=5, n_redundant=2,
                           n_classes=2, weights=[0.7], class_sep=0.7, random_state=15)

In [78]:
#y[y==0] = -1
y

array([0, 1, 0, ..., 1, 0, 1])

In [79]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train,X_val,y_train,y_val = train_test_split(X_train,y_train,test_size=0.2,random_state=24)
print(X_train.shape, y_train.shape)
print(X_val.shape, y_val.shape)
print(X_test.shape, y_test.shape)

(3200, 5) (3200,)
(800, 5) (800,)
(1000, 5) (1000,)


### Pseudo code

clf = SVC(gamma=0.001, C=100.)<br>
clf.fit(Xtrain, ytrain)

<font color='green'>def</font> <font color='blue'>decision_function</font>(Xcv, ...): #use appropriate parameters <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='green'>for</font> a data point $x_q$ <font color='green'>in</font> Xcv: <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<font color='grey'>#write code to implement $(\sum_{i=1}^{\text{all the support vectors}}(y_{i}\alpha_{i}K(x_{i},x_{q})) + intercept)$, here the values $y_i$, $\alpha_{i}$, and $intercept$ can be obtained from the trained model</font><br>
   <font color='green'>return</font> <font color='grey'><i># the decision_function output for all the data points in the Xcv</i></font>
    
fcv = decision_function(Xcv, ...)  <i># based on your requirement you can pass any other parameters </i>

<b>Note</b>: Make sure the values you get as fcv, should be equal to outputs of clf.decision_function(Xcv)


In [80]:
# you can write your code here
gamma = 0.001
clf = SVC(gamma=gamma, C=100)
clf.fit(X_train,y_train)

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [81]:
def K(xq):
    val = 0
    for alpha,xi in zip(clf.dual_coef_[0],clf.support_vectors_): #the dual_coef_[i] contains label[i]*alpha[i]
        val += alpha*np.exp(-gamma*np.linalg.norm(xi-xq)**2) 
    return val+clf.intercept_.item()

In [82]:
def dec_fun(X_val):
    fcv = []
    for xq in X_val:
        fcv.append(K(xq))
    return(np.array(fcv))

In [83]:
dec_fun(X_val)

array([-2.69065026, -4.01123357, -2.48966713,  1.35046624, -2.59528514,
       -2.30501509,  1.41770579, -0.43831055, -2.43467245,  1.64358234,
       -2.30755842, -1.28262667,  1.43221735, -3.6640798 ,  1.73676085,
        1.64844048, -2.96446415, -2.27370879, -3.87103916, -1.38041339,
       -2.2897439 ,  1.35763225, -1.58450812, -2.71269654, -2.51785957,
        1.59448568, -2.91446027, -1.14699993, -1.27549829,  1.7822262 ,
       -3.69602334, -2.42593879,  1.89868102, -0.08398933,  1.66267593,
        1.4698012 , -3.25798546, -3.45051326, -0.09489246,  0.09058346,
       -2.02851987,  1.1774024 , -2.91011102, -2.6490935 , -0.40433583,
        2.08016708, -3.4494807 , -1.04782432,  0.58895649, -2.34283292,
       -3.98910774, -0.49050617, -3.57258524, -1.28506826, -1.3270522 ,
       -2.62622674, -2.85807125, -2.08467843, -2.3924406 ,  2.01477986,
       -2.63538773,  0.94164139, -1.16507049,  0.23152835,  2.95486314,
       -0.14166578, -3.1806057 , -2.06875309,  2.14263081,  1.76

In [84]:
clf.decision_function(X_val)

array([-2.69065026, -4.01123357, -2.48966713,  1.35046624, -2.59528514,
       -2.30501509,  1.41770579, -0.43831055, -2.43467245,  1.64358234,
       -2.30755842, -1.28262667,  1.43221735, -3.6640798 ,  1.73676085,
        1.64844048, -2.96446415, -2.27370879, -3.87103916, -1.38041339,
       -2.2897439 ,  1.35763225, -1.58450812, -2.71269654, -2.51785957,
        1.59448568, -2.91446027, -1.14699993, -1.27549829,  1.7822262 ,
       -3.69602334, -2.42593879,  1.89868102, -0.08398933,  1.66267593,
        1.4698012 , -3.25798546, -3.45051326, -0.09489246,  0.09058346,
       -2.02851987,  1.1774024 , -2.91011102, -2.6490935 , -0.40433583,
        2.08016708, -3.4494807 , -1.04782432,  0.58895649, -2.34283292,
       -3.98910774, -0.49050617, -3.57258524, -1.28506826, -1.3270522 ,
       -2.62622674, -2.85807125, -2.08467843, -2.3924406 ,  2.01477986,
       -2.63538773,  0.94164139, -1.16507049,  0.23152835,  2.95486314,
       -0.14166578, -3.1806057 , -2.06875309,  2.14263081,  1.76

<h2><font color='Geen'> 9F: Implementing Platt Scaling to find P(Y==1|X)</font></h2>

Check this <a href='https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a'>PDF</a>
<img src='https://i.imgur.com/CAMnVnh.png'>


## TASK F


> 4. Apply SGD algorithm with ($f_{cv}$, $y_{cv}$) and find the weight $W$ intercept $b$ ```Note: here our data is of one dimensional so we will have a one dimensional weight vector i.e W.shape (1,)``` 

> Note1: Don't forget to change the values of $y_{cv}$ as mentioned in the above image. you will calculate y+, y- based on data points in train data

> Note2: the Sklearn's SGD algorithm doesn't support the real valued outputs, you need to use the code that was done in the `'Logistic Regression with SGD and L2'` Assignment after modifying loss function, and use same parameters that used in that assignment.
<img src='https://i.imgur.com/zKYE9Oc.png'>
if Y[i] is 1, it will be replaced with y+ value else it will replaced with y- value

> 5. For a given data point from $X_{test}$, $P(Y=1|X) = \frac{1}{1+exp(-(W*f_{test}+ b))}$ where ` `$f_{test}$ ```= decision_function(```$X_{test}$```)```, W and b will be learned as metioned in the above step

__Note: in the above algorithm, the steps 2, 4 might need hyper parameter tuning, To reduce the complexity of the assignment we are excluding the hyerparameter tuning part, but intrested students can try that__

In [85]:
fcv = dec_fun(X_val)
y_val_cpy = y_val.astype('float')
unique,counts = np.unique(y_val_cpy,return_counts=True)
print(unique,counts)
y_val_cpy[y_val_cpy==unique[0]]=1.0/(counts[0]+2)
y_val_cpy[y_val_cpy==unique[1]]=(counts[1]+1.0)/(counts[1]+2)

[0. 1.] [550 250]


In [86]:
def sigmoid(w,x,b):
    return 1/(1+np.exp(-(w@x+b)))

In [87]:
def update_weights(X,y,w,b,lamda,alpha,N):
    w_new = (1-alpha*lamda/N)*w + alpha*X*(y-sigmoid(w,X.T,b))
    b_new = b + alpha*(y-sigmoid(w,X.T,b))
    return w_new,b_new

In [88]:
def next_batch(X, y, batchSize):
    # loop over our dataset `X` in mini-batches of size `batchSize`
    for i in np.arange(0, X.shape[0], batchSize):
        # yield a tuple of the current batched data and labels
        yield (X[i:i + batchSize], y[i:i + batchSize])

In [89]:
def compute_log_loss(A,n):# your code
    loss=0
    for Y in A:
        loss += Y[0]*math.log(Y[1])+(1-Y[0])*math.log(1-Y[1]) 
    loss = -loss/n
    return loss

In [95]:
w = np.zeros((1,))
b = 0
lamda  = 0.0001
alpha = 0.0001
N = len(fcv)
w.shape

(1,)

In [96]:
import math
lossHistoryTrain = []
lossHistoryTest = []
epochs = range(1,30)
for epoch in epochs:
    # initialize the total loss for the epoch
    epochLossTrain = []
    epochLossTest = []
    # loop over our data in batches
    for (batchX, batchY) in next_batch(fcv, y_val_cpy, 1):
        preds = sigmoid(w,batchX,b)
        loss = -(batchY*math.log(preds)+(1-batchY)*math.log(1-preds))
        epochLossTrain.append(loss)
        w, b = update_weights(batchX,batchY,w,b,lamda,alpha,N)
        
    avgLossTrain = np.average(epochLossTrain)
    lossHistoryTrain.append(avgLossTrain)
    print("iteration:{}".format(epoch))
    print("Training Loss:{}".format(avgLossTrain))
    y_pred = [sigmoid(w,x.reshape(-1,1),b) for x in dec_fun(X_test)]
    avgLossTest = compute_log_loss(zip(y_test,y_pred),len(y_test))
    lossHistoryTest.append(avgLossTest)
    print("Test Loss:{}".format(avgLossTest))
    print('='*75)
print('Final Weights:')
print(w)
print('Final Intercept:',b)

iteration:1
Training Loss:0.6552991440625178
Test Loss:0.6216799191875771
iteration:2
Training Loss:0.5899504093091643
Test Loss:0.5645912433935767
iteration:3
Training Loss:0.5376450468017597
Test Loss:0.5185955466686065
iteration:4
Training Loss:0.4953452949234486
Test Loss:0.4811179312138139
iteration:5
Training Loss:0.4607177842269182
Test Loss:0.4502053772357796
iteration:6
Training Loss:0.43201116620223556
Test Loss:0.4243957071932323
iteration:7
Training Loss:0.40792005329857134
Test Loss:0.40259569163253994
iteration:8
Training Loss:0.38746914857339987
Test Loss:0.3839836238254411
iteration:9
Training Loss:0.3699243012691913
Test Loss:0.3679364008743245
iteration:10
Training Loss:0.35472727885274635
Test Loss:0.3539765039079248
iteration:11
Training Loss:0.34144882027064943
Test Loss:0.3417338531083492
iteration:12
Training Loss:0.32975501183164174
Test Loss:0.3309183847754427
iteration:13
Training Loss:0.31938314266484286
Test Loss:0.3213002439334413
iteration:14
Training Loss


If any one wants to try other calibration algorithm istonic regression also please check these tutorials

1. http://fa.bianp.net/blog/tag/scikit-learn.html#fn:1

2. https://drive.google.com/open?id=1MzmA7QaP58RDzocB0RBmRiWfl7Co_VJ7

3. https://drive.google.com/open?id=133odBinMOIVb_rh_GQxxsyMRyW-Zts7a

4. https://stat.fandom.com/wiki/Isotonic_regression#Pool_Adjacent_Violators_Algorithm
